import { PrismaClient, Difficulty } from '@prisma/client';

const prisma = new PrismaClient();

const cards = [
  // GREETINGS (25)
  { word: 'Kamusta', phonetic: 'ka-mus-ta', meaning: 'Hello / How are you?', exampleFil: 'Kamusta ka?', exampleEng: 'How are you?', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Magandang umaga', phonetic: 'ma-gan-dang u-ma-ga', meaning: 'Good morning', exampleFil: 'Magandang umaga po!', exampleEng: 'Good morning (respectful)!', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Magandang hapon', phonetic: 'ma-gan-dang ha-pon', meaning: 'Good afternoon', exampleFil: 'Magandang hapon sa inyo.', exampleEng: 'Good afternoon to you all.', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Magandang gabi', phonetic: 'ma-gan-dang ga-bi', meaning: 'Good evening', exampleFil: 'Magandang gabi, pare.', exampleEng: 'Good evening, friend.', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Paalam', phonetic: 'pa-a-lam', meaning: 'Goodbye', exampleFil: 'Paalam na, ingat ka.', exampleEng: 'Goodbye, take care.', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Salamat', phonetic: 'sa-la-mat', meaning: 'Thank you', exampleFil: 'Salamat sa tulong mo.', exampleEng: 'Thank you for your help.', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Walang anuman', phonetic: 'wa-lang a-nu-man', meaning: "You're welcome", exampleFil: 'Walang anuman, kaibigan.', exampleEng: "You're welcome, friend.", category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Po', phonetic: 'po', meaning: 'Respect particle (statement)', exampleFil: 'Oo po.', exampleEng: 'Yes (respectful).', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Opo', phonetic: 'o-po', meaning: 'Yes (respectful)', exampleFil: 'Opo, nandito na po ako.', exampleEng: "Yes, I'm already here (respectful).", category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Hindi po', phonetic: 'hin-di po', meaning: 'No (respectful)', exampleFil: 'Hindi po ako sigurado.', exampleEng: "I'm not sure (respectful).", category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Ingat ka', phonetic: 'i-ngat ka', meaning: 'Take care', exampleFil: 'Ingat ka sa daan.', exampleEng: 'Take care on the road.', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Kumain ka na ba?', phonetic: 'ku-main ka na ba', meaning: 'Have you eaten yet?', exampleFil: 'Kumain ka na ba? Kain tayo!', exampleEng: 'Have you eaten yet? Let us eat!', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Saan ka pupunta?', phonetic: 'sa-an ka pu-pun-ta', meaning: 'Where are you going?', exampleFil: 'Saan ka pupunta mamaya?', exampleEng: 'Where are you going later?', category: 'greetings', difficulty: Difficulty.intermediate },
  { word: 'Matagal na', phonetic: 'ma-ta-gal na', meaning: 'Long time (no see)', exampleFil: 'Matagal na tayong hindi nagkita!', exampleEng: "It's been a long time since we've seen each other!", category: 'greetings', difficulty: Difficulty.intermediate },
  { word: 'Kumusta ang pamilya?', phonetic: 'ku-mus-ta ang pa-mil-ya', meaning: 'How is the family?', exampleFil: 'Kumusta ang pamilya mo?', exampleEng: 'How is your family?', category: 'greetings', difficulty: Difficulty.intermediate },
  { word: 'Mabuti naman', phonetic: 'ma-bu-ti na-man', meaning: 'Pretty good / Fine', exampleFil: 'Mabuti naman, ikaw?', exampleEng: "Pretty good, and you?", category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Ano ang pangalan mo?', phonetic: 'a-no ang pa-nga-lan mo', meaning: 'What is your name?', exampleFil: 'Ano ang pangalan mo?', exampleEng: 'What is your name?', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Ang pangalan ko ay', phonetic: 'ang pa-nga-lan ko ay', meaning: 'My name is', exampleFil: 'Ang pangalan ko ay Maria.', exampleEng: 'My name is Maria.', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Ikinagagalak kong makilala ka', phonetic: 'i-ki-na-ga-ga-lak kong ma-ki-la-la ka', meaning: 'Nice to meet you', exampleFil: 'Ikinagagalak kong makilala ka.', exampleEng: 'Nice to meet you.', category: 'greetings', difficulty: Difficulty.intermediate },
  { word: 'Taga-saan ka?', phonetic: 'ta-ga-sa-an ka', meaning: 'Where are you from?', exampleFil: 'Taga-saan ka ba?', exampleEng: 'Where are you from?', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Taga-Inglatera ako', phonetic: 'ta-ga-ing-la-te-ra a-ko', meaning: 'I am from England', exampleFil: 'Taga-Inglatera ako.', exampleEng: 'I am from England.', category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Magkita tayo ulit', phonetic: 'mag-ki-ta ta-yo u-lit', meaning: "Let's meet again", exampleFil: 'Magkita tayo ulit bukas.', exampleEng: "Let's meet again tomorrow.", category: 'greetings', difficulty: Difficulty.intermediate },
  { word: 'Hanggang sa muli', phonetic: 'hang-gang sa mu-li', meaning: 'Until next time', exampleFil: 'Hanggang sa muli, kaibigan.', exampleEng: 'Until next time, friend.', category: 'greetings', difficulty: Difficulty.intermediate },
  { word: 'Nandito na ako', phonetic: 'nan-di-to na a-ko', meaning: "I'm here now", exampleFil: 'Nandito na ako, sorry sa huli.', exampleEng: "I'm here now, sorry for being late.", category: 'greetings', difficulty: Difficulty.beginner },
  { word: 'Sige', phonetic: 'si-ge', meaning: 'Okay / Alright / Bye then', exampleFil: 'Sige, kita tayo bukas.', exampleEng: "Alright, see you tomorrow.", category: 'greetings', difficulty: Difficulty.beginner },

  // FOOD (25)
  { word: 'Kanin', phonetic: 'ka-nin', meaning: 'Rice (cooked)', exampleFil: 'Gusto ko ng kanin at ulam.', exampleEng: 'I want rice and a dish.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Ulam', phonetic: 'u-lam', meaning: 'Main dish (eaten with rice)', exampleFil: 'Ano ang ulam natin ngayon?', exampleEng: "What's our dish today?", category: 'food', difficulty: Difficulty.beginner },
  { word: 'Adobo', phonetic: 'a-do-bo', meaning: 'Adobo (vinegar-braised meat)', exampleFil: 'Ang adobo ang paboritong pagkain ng Pilipino.', exampleEng: "Adobo is the Filipino's favourite food.", category: 'food', difficulty: Difficulty.beginner },
  { word: 'Sinigang', phonetic: 'si-ni-gang', meaning: 'Sinigang (tamarind sour soup)', exampleFil: 'Masarap ang sinigang na baboy.', exampleEng: 'Pork sinigang is delicious.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Lechon', phonetic: 'le-chon', meaning: 'Roasted suckling pig', exampleFil: 'May lechon sa handaan.', exampleEng: 'There is lechon at the party.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Lumpia', phonetic: 'lum-pya', meaning: 'Spring rolls', exampleFil: 'Gusto ko ng lumpia shanghai.', exampleEng: 'I want Shanghai spring rolls.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Pancit', phonetic: 'pan-sit', meaning: 'Noodle dish', exampleFil: 'Kumain tayo ng pancit sa kaarawan.', exampleEng: "Let's eat pancit at the birthday.", category: 'food', difficulty: Difficulty.beginner },
  { word: 'Masarap', phonetic: 'ma-sa-rap', meaning: 'Delicious / Tasty', exampleFil: 'Masarap ang pagkain dito.', exampleEng: 'The food here is delicious.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Gutom', phonetic: 'gu-tom', meaning: 'Hungry', exampleFil: 'Gutom na ako!', exampleEng: "I'm already hungry!", category: 'food', difficulty: Difficulty.beginner },
  { word: 'Busog', phonetic: 'bu-sog', meaning: 'Full (after eating)', exampleFil: 'Busog na ako, salamat.', exampleEng: "I'm full, thank you.", category: 'food', difficulty: Difficulty.beginner },
  { word: 'Tubig', phonetic: 'tu-big', meaning: 'Water', exampleFil: 'Pakihingi ng tubig.', exampleEng: 'Please give me water.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Kape', phonetic: 'ka-pe', meaning: 'Coffee', exampleFil: 'Gusto mo ng kape?', exampleEng: 'Do you want coffee?', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Merienda', phonetic: 'me-ryen-da', meaning: 'Afternoon snack', exampleFil: 'Oras na ng merienda.', exampleEng: "It's snack time.", category: 'food', difficulty: Difficulty.beginner },
  { word: 'Taho', phonetic: 'ta-ho', meaning: 'Silken tofu with syrup and tapioca', exampleFil: 'Taho! Taho! sabi ng magtataho.', exampleEng: '"Taho! Taho!" said the taho vendor.', category: 'food', difficulty: Difficulty.intermediate },
  { word: 'Halo-halo', phonetic: 'ha-lo ha-lo', meaning: 'Mixed shaved ice dessert', exampleFil: 'Masarap ang halo-halo sa tag-araw.', exampleEng: 'Halo-halo is delicious in summer.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Palengke', phonetic: 'pa-leng-ke', meaning: 'Market / Wet market', exampleFil: 'Pupunta ako sa palengke para bumili ng gulay.', exampleEng: "I'm going to the market to buy vegetables.", category: 'food', difficulty: Difficulty.beginner },
  { word: 'Magkano?', phonetic: 'mag-ka-no', meaning: 'How much?', exampleFil: 'Magkano ang isang kilo ng mangga?', exampleEng: 'How much is one kilo of mango?', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Mahal', phonetic: 'ma-hal', meaning: 'Expensive (also: love)', exampleFil: 'Mahal ang presyo ng karne ngayon.', exampleEng: 'The price of meat is expensive now.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Mura', phonetic: 'mu-ra', meaning: 'Cheap / Affordable', exampleFil: 'Mura ang gulay dito.', exampleEng: 'The vegetables here are cheap.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Mangga', phonetic: 'mang-ga', meaning: 'Mango', exampleFil: 'Gusto ko ng hilaw na mangga.', exampleEng: 'I like unripe mango.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Isda', phonetic: 'is-da', meaning: 'Fish', exampleFil: 'Luto tayo ng isda ngayon.', exampleEng: "Let's cook fish today.", category: 'food', difficulty: Difficulty.beginner },
  { word: 'Manok', phonetic: 'ma-nok', meaning: 'Chicken', exampleFil: 'Gusto ko ng pritong manok.', exampleEng: 'I want fried chicken.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Baboy', phonetic: 'ba-boy', meaning: 'Pork / Pig', exampleFil: 'Wala kaming baboy ngayon.', exampleEng: "We don't have pork today.", category: 'food', difficulty: Difficulty.beginner },
  { word: 'Gulay', phonetic: 'gu-lay', meaning: 'Vegetables', exampleFil: 'Kumain ng gulay para maging malusog.', exampleEng: 'Eat vegetables to be healthy.', category: 'food', difficulty: Difficulty.beginner },
  { word: 'Kain tayo!', phonetic: 'ka-in ta-yo', meaning: "Let's eat!", exampleFil: 'Handa na ang pagkain, kain tayo!', exampleEng: "The food is ready, let's eat!", category: 'food', difficulty: Difficulty.beginner },

  // FAMILY (25)
  { word: 'Pamilya', phonetic: 'pa-mil-ya', meaning: 'Family', exampleFil: 'Mahalaga ang pamilya sa mga Pilipino.', exampleEng: 'Family is important to Filipinos.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Nanay', phonetic: 'na-nay', meaning: 'Mother / Mum', exampleFil: 'Luto ang nanay ko ngayon.', exampleEng: 'My mum is cooking now.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Tatay', phonetic: 'ta-tay', meaning: 'Father / Dad', exampleFil: 'Nasa trabaho ang tatay ko.', exampleEng: 'My dad is at work.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Kuya', phonetic: 'ku-ya', meaning: 'Older brother (also used for older males)', exampleFil: 'Kuya, tulungan mo ako.', exampleEng: 'Big brother, help me.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Ate', phonetic: 'a-te', meaning: 'Older sister (also used for older females)', exampleFil: 'Ate Maya ang guro ko.', exampleEng: 'Ate Maya is my teacher.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Bunso', phonetic: 'bun-so', meaning: 'Youngest sibling', exampleFil: 'Ako ang bunso sa aming pamilya.', exampleEng: 'I am the youngest in our family.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Lolo', phonetic: 'lo-lo', meaning: 'Grandfather', exampleFil: 'Malusog pa ang lolo ko.', exampleEng: 'My grandfather is still healthy.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Lola', phonetic: 'lo-la', meaning: 'Grandmother', exampleFil: 'Mabait ang lola ko.', exampleEng: 'My grandmother is kind.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Tito', phonetic: 'ti-to', meaning: 'Uncle', exampleFil: 'Tito ko ang nagbigay ng regalo.', exampleEng: 'My uncle gave the gift.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Tita', phonetic: 'ti-ta', meaning: 'Aunt', exampleFil: 'Nag-alaga sa akin si Tita.', exampleEng: 'Auntie took care of me.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Pinsan', phonetic: 'pin-san', meaning: 'Cousin', exampleFil: 'Marami akong pinsan sa probinsya.', exampleEng: 'I have many cousins in the province.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Kapatid', phonetic: 'ka-pa-tid', meaning: 'Sibling (brother or sister)', exampleFil: 'Dalawa ang kapatid ko.', exampleEng: 'I have two siblings.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Anak', phonetic: 'a-nak', meaning: 'Child / Son / Daughter', exampleFil: 'Anak ko si Juan.', exampleEng: 'Juan is my child.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Asawa', phonetic: 'a-sa-wa', meaning: 'Spouse (husband or wife)', exampleFil: 'Nasa bahay ang asawa ko.', exampleEng: 'My spouse is at home.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Inaanak', phonetic: 'i-na-a-nak', meaning: 'Godchild', exampleFil: 'Ang inaanak ko ay si Liza.', exampleEng: 'My godchild is Liza.', category: 'family', difficulty: Difficulty.intermediate },
  { word: 'Ninong', phonetic: 'ni-nong', meaning: 'Godfather', exampleFil: 'Si Kuya Roel ang ninong ko.', exampleEng: 'Kuya Roel is my godfather.', category: 'family', difficulty: Difficulty.intermediate },
  { word: 'Ninang', phonetic: 'ni-nang', meaning: 'Godmother', exampleFil: 'Ninang ko si Tita Rosa.', exampleEng: 'My godmother is Tita Rosa.', category: 'family', difficulty: Difficulty.intermediate },
  { word: 'Biyenan', phonetic: 'bi-ye-nan', meaning: 'Parent-in-law', exampleFil: 'Mabait ang biyenan ko.', exampleEng: 'My in-law is kind.', category: 'family', difficulty: Difficulty.intermediate },
  { word: 'Hipag', phonetic: 'hi-pag', meaning: 'Sister-in-law', exampleFil: 'Ang hipag ko ay guro.', exampleEng: 'My sister-in-law is a teacher.', category: 'family', difficulty: Difficulty.intermediate },
  { word: 'Bayaw', phonetic: 'ba-yaw', meaning: 'Brother-in-law', exampleFil: 'Negosyante ang bayaw ko.', exampleEng: 'My brother-in-law is a businessman.', category: 'family', difficulty: Difficulty.intermediate },
  { word: 'Mahal kita', phonetic: 'ma-hal ki-ta', meaning: 'I love you', exampleFil: 'Mahal kita, Nanay.', exampleEng: 'I love you, Mum.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Alaga', phonetic: 'a-la-ga', meaning: 'To care for / raise', exampleFil: 'Inaalaga ng nanay ang bata.', exampleEng: 'The mother is caring for the child.', category: 'family', difficulty: Difficulty.intermediate },
  { word: 'Reunion', phonetic: 're-yu-nyon', meaning: 'Family reunion', exampleFil: 'May reunion kami tuwing Pasko.', exampleEng: 'We have a reunion every Christmas.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Magulang', phonetic: 'ma-gu-lang', meaning: 'Parent(s)', exampleFil: 'Mahal ko ang aking mga magulang.', exampleEng: 'I love my parents.', category: 'family', difficulty: Difficulty.beginner },
  { word: 'Kamag-anak', phonetic: 'ka-mag-a-nak', meaning: 'Relative', exampleFil: 'Maraming kamag-anak ang pumunta.', exampleEng: 'Many relatives came.', category: 'family', difficulty: Difficulty.intermediate },

  // NUMBERS (25)
  { word: 'Isa', phonetic: 'i-sa', meaning: 'One', exampleFil: 'Isa lang ang gusto ko.', exampleEng: 'I only want one.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Dalawa', phonetic: 'da-la-wa', meaning: 'Two', exampleFil: 'Dalawang tasa ng kape.', exampleEng: 'Two cups of coffee.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Tatlo', phonetic: 'tat-lo', meaning: 'Three', exampleFil: 'Tatlong araw pa.', exampleEng: 'Three more days.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Apat', phonetic: 'a-pat', meaning: 'Four', exampleFil: 'Apat na tao.', exampleEng: 'Four people.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Lima', phonetic: 'li-ma', meaning: 'Five', exampleFil: 'Lima piso lang.', exampleEng: 'Only five pesos.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Anim', phonetic: 'a-nim', meaning: 'Six', exampleFil: 'Anim na mansanas.', exampleEng: 'Six apples.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Pito', phonetic: 'pi-to', meaning: 'Seven', exampleFil: 'Pito ang klase ko ngayong linggo.', exampleEng: 'I have seven classes this week.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Walo', phonetic: 'wa-lo', meaning: 'Eight', exampleFil: 'Walo na ang oras.', exampleEng: "It's eight o'clock.", category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Siyam', phonetic: 'si-yam', meaning: 'Nine', exampleFil: 'Siyam na estudyante.', exampleEng: 'Nine students.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Sampu', phonetic: 'sam-pu', meaning: 'Ten', exampleFil: 'Sampung minuto pa lang.', exampleEng: 'Only ten more minutes.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Labinisa', phonetic: 'la-bin-i-sa', meaning: 'Eleven', exampleFil: 'Labinisang piso ang sukli ko.', exampleEng: 'My change is eleven pesos.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Labindalawa', phonetic: 'la-bin-da-la-wa', meaning: 'Twelve', exampleFil: 'Labindalawang buwan sa isang taon.', exampleEng: 'Twelve months in a year.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Dalawampu', phonetic: 'da-la-wam-pu', meaning: 'Twenty', exampleFil: 'Dalawampung piso.', exampleEng: 'Twenty pesos.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Tatlumpu', phonetic: 'tat-lum-pu', meaning: 'Thirty', exampleFil: 'Tatlumpung minuto.', exampleEng: 'Thirty minutes.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Apatnapu', phonetic: 'a-pat-na-pu', meaning: 'Forty', exampleFil: 'Apatnapung taon na siya.', exampleEng: 'He/she is forty years old.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Limampu', phonetic: 'li-mam-pu', meaning: 'Fifty', exampleFil: 'Limampung piso ang bayad.', exampleEng: 'The payment is fifty pesos.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Isang daan', phonetic: 'i-sang da-an', meaning: 'One hundred', exampleFil: 'Isang daang piso lang.', exampleEng: 'Only one hundred pesos.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Kalahati', phonetic: 'ka-la-ha-ti', meaning: 'Half', exampleFil: 'Kalahati lang ang gusto ko.', exampleEng: 'I only want half.', category: 'numbers', difficulty: Difficulty.intermediate },
  { word: 'Ilan?', phonetic: 'i-lan', meaning: 'How many?', exampleFil: 'Ilan ang gusto mo?', exampleEng: 'How many do you want?', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Lahat', phonetic: 'la-hat', meaning: 'All / Everything', exampleFil: 'Lahat ng tao ay nandito.', exampleEng: 'Everyone is here.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Wala', phonetic: 'wa-la', meaning: 'None / Zero / Not here', exampleFil: 'Wala nang natira.', exampleEng: "There's none left.", category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Marami', phonetic: 'ma-ra-mi', meaning: 'Many / A lot', exampleFil: 'Maraming tao sa palengke.', exampleEng: 'There are many people in the market.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Kaunti', phonetic: 'ka-un-ti', meaning: 'A little / Few', exampleFil: 'Kaunti na lang ang natirang pagkain.', exampleEng: 'There is only a little food left.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Una', phonetic: 'u-na', meaning: 'First', exampleFil: 'Una kang kumain.', exampleEng: 'You eat first.', category: 'numbers', difficulty: Difficulty.beginner },
  { word: 'Huli', phonetic: 'hu-li', meaning: 'Last / Late', exampleFil: 'Huli na tayo!', exampleEng: "We're late!", category: 'numbers', difficulty: Difficulty.beginner },

  // TRANSPORT (25)
  { word: 'Jeepney', phonetic: 'jip-ni', meaning: 'Jeepney (iconic Filipino transport)', exampleFil: 'Sasakay tayo ng jeepney.', exampleEng: "Let's ride the jeepney.", category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Tricycle', phonetic: 'tri-si-kel', meaning: 'Tricycle (motorbike with sidecar)', exampleFil: 'Tricycle ang sasakay ko papunta sa bahay.', exampleEng: "I'll take a tricycle going home.", category: 'transport', difficulty: Difficulty.beginner },
  { word: 'LRT / MRT', phonetic: 'el-ar-ti / em-ar-ti', meaning: 'Light Rail / Metro Rail Transit', exampleFil: 'Mas mabilis kung sumasakay ng MRT.', exampleEng: 'It is faster if you ride the MRT.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Barko', phonetic: 'bar-ko', meaning: 'Ship / Boat', exampleFil: 'Barko ang gagamitin namin papunta sa isla.', exampleEng: "We'll use a ship to get to the island.", category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Eroplano', phonetic: 'e-ro-pla-no', meaning: 'Aeroplane', exampleFil: 'Sumakay kami ng eroplano papunta sa Cebu.', exampleEng: 'We rode an aeroplane going to Cebu.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Taxi', phonetic: 'tak-si', meaning: 'Taxi', exampleFil: 'Tumawag tayo ng taxi.', exampleEng: "Let's call a taxi.", category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Daan', phonetic: 'da-an', meaning: 'Road / Path / Way', exampleFil: 'Alin ang tamang daan?', exampleEng: 'Which is the right way?', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Kaliwa', phonetic: 'ka-li-wa', meaning: 'Left', exampleFil: 'Lumiko sa kaliwa.', exampleEng: 'Turn left.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Kanan', phonetic: 'ka-nan', meaning: 'Right', exampleFil: 'Nasa kanan ang tindahan.', exampleEng: 'The store is on the right.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Diretso', phonetic: 'di-ret-so', meaning: 'Straight ahead', exampleFil: 'Diretso ka lang.', exampleEng: 'Just go straight.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Hinto', phonetic: 'hin-to', meaning: 'Stop', exampleFil: 'Hinto muna dito.', exampleEng: 'Stop here for a moment.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Paradahan', phonetic: 'pa-ra-da-han', meaning: 'Parking area / Terminal', exampleFil: 'Nasa paradahan ang jeepney.', exampleEng: 'The jeepney is at the terminal.', category: 'transport', difficulty: Difficulty.intermediate },
  { word: 'Paliparan', phonetic: 'pa-li-pa-ran', meaning: 'Airport', exampleFil: 'Dadalhin kita sa paliparan.', exampleEng: "I'll bring you to the airport.", category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Istasyon', phonetic: 'is-tas-yon', meaning: 'Station', exampleFil: 'Saan ang pinakamalapit na istasyon?', exampleEng: 'Where is the nearest station?', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Bayad po!', phonetic: 'ba-yad po', meaning: 'Fare payment (on jeepney)', exampleFil: 'Bayad po, diretso lang.', exampleEng: 'Fare, going straight ahead.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Para po!', phonetic: 'pa-ra po', meaning: 'Stop please! (on jeepney)', exampleFil: 'Para po dito sa tabi.', exampleEng: 'Stop here on the side please.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Trapiko', phonetic: 'tra-pi-ko', meaning: 'Traffic', exampleFil: 'Malala ang trapiko ngayon.', exampleEng: 'The traffic is bad now.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Malayo', phonetic: 'ma-la-yo', meaning: 'Far', exampleFil: 'Malayo pa ba ang Maynila?', exampleEng: 'Is Manila still far?', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Malapit', phonetic: 'ma-la-pit', meaning: 'Near / Close', exampleFil: 'Malapit na tayo.', exampleEng: "We're almost there.", category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Pasada', phonetic: 'pa-sa-da', meaning: 'Route / Trip', exampleFil: 'Anong pasada ng jeepney na ito?', exampleEng: 'What is the route of this jeepney?', category: 'transport', difficulty: Difficulty.intermediate },
  { word: 'Sukli', phonetic: 'suk-li', meaning: 'Change (money)', exampleFil: 'Heto ang sukli mo.', exampleEng: 'Here is your change.', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Pamasahe', phonetic: 'pa-ma-sa-he', meaning: 'Fare', exampleFil: 'Magkano ang pamasahe papunta doon?', exampleEng: 'How much is the fare going there?', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Sakay', phonetic: 'sa-kay', meaning: 'To ride / board', exampleFil: 'Saan tayo sasakay?', exampleEng: 'Where will we board?', category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Bababa po!', phonetic: 'ba-ba-ba po', meaning: "I'm getting off! (transport)", exampleFil: 'Bababa po dito sa kanto.', exampleEng: "I'm getting off at the corner.", category: 'transport', difficulty: Difficulty.beginner },
  { word: 'Biyahe', phonetic: 'bi-ya-he', meaning: 'Journey / Trip', exampleFil: 'Matagal ang biyahe papunta sa Mindanao.', exampleEng: 'The journey to Mindanao is long.', category: 'transport', difficulty: Difficulty.beginner },

  // HOME (25)
  { word: 'Bahay', phonetic: 'ba-hay', meaning: 'House / Home', exampleFil: 'Nasa bahay ako ngayon.', exampleEng: "I'm at home now.", category: 'home', difficulty: Difficulty.beginner },
  { word: 'Sala', phonetic: 'sa-la', meaning: 'Living room', exampleFil: 'Nanonood ng TV sa sala.', exampleEng: 'Watching TV in the living room.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Kusina', phonetic: 'ku-si-na', meaning: 'Kitchen', exampleFil: 'Nagluluto ang nanay sa kusina.', exampleEng: 'Mum is cooking in the kitchen.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Kwarto', phonetic: 'kwar-to', meaning: 'Bedroom / Room', exampleFil: 'Nasa kwarto ako nag-aaral.', exampleEng: "I'm studying in my room.", category: 'home', difficulty: Difficulty.beginner },
  { word: 'Banyo', phonetic: 'ban-yo', meaning: 'Bathroom', exampleFil: 'Nasa banyo siya ngayon.', exampleEng: 'He/she is in the bathroom now.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Pintuan', phonetic: 'pin-tu-an', meaning: 'Door', exampleFil: 'Isara mo ang pintuan.', exampleEng: 'Close the door.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Bintana', phonetic: 'bin-ta-na', meaning: 'Window', exampleFil: 'Buksan mo ang bintana.', exampleEng: 'Open the window.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Hagdan', phonetic: 'hag-dan', meaning: 'Stairs', exampleFil: 'Mag-ingat sa hagdan.', exampleEng: 'Be careful on the stairs.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Bubong', phonetic: 'bu-bong', meaning: 'Roof', exampleFil: 'May butas ang bubong.', exampleEng: 'There is a hole in the roof.', category: 'home', difficulty: Difficulty.intermediate },
  { word: 'Bakuran', phonetic: 'ba-ku-ran', meaning: 'Yard / Garden', exampleFil: 'Naglalaro ang mga bata sa bakuran.', exampleEng: 'The children are playing in the yard.', category: 'home', difficulty: Difficulty.intermediate },
  { word: 'Mesa', phonetic: 'me-sa', meaning: 'Table', exampleFil: 'Kumain tayo sa mesa.', exampleEng: "Let's eat at the table.", category: 'home', difficulty: Difficulty.beginner },
  { word: 'Upuan', phonetic: 'u-pu-an', meaning: 'Chair / Seat', exampleFil: 'Maupo ka sa upuan.', exampleEng: 'Sit on the chair.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Kama', phonetic: 'ka-ma', meaning: 'Bed', exampleFil: 'Matulog na tayo sa kama.', exampleEng: "Let's sleep in bed.", category: 'home', difficulty: Difficulty.beginner },
  { word: 'Ref / Pridyider', phonetic: 'prid-yi-der', meaning: 'Refrigerator / Fridge', exampleFil: 'Nasa ref ang pagkain.', exampleEng: 'The food is in the fridge.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Lababo', phonetic: 'la-ba-bo', meaning: 'Sink', exampleFil: 'Hugasan mo ang plato sa lababo.', exampleEng: 'Wash the plates in the sink.', category: 'home', difficulty: Difficulty.intermediate },
  { word: 'Ilaw', phonetic: 'i-law', meaning: 'Light / Lamp', exampleFil: 'Patayin mo ang ilaw.', exampleEng: 'Turn off the light.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Aircon', phonetic: 'er-kon', meaning: 'Air conditioner', exampleFil: 'Malamig dahil nakabukas ang aircon.', exampleEng: "It's cold because the aircon is on.", category: 'home', difficulty: Difficulty.beginner },
  { word: 'Malinis', phonetic: 'ma-li-nis', meaning: 'Clean', exampleFil: 'Malinis ang bahay nila.', exampleEng: 'Their house is clean.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Maayos', phonetic: 'ma-a-yos', meaning: 'Neat / Orderly / Fixed', exampleFil: 'Maayos mo ang kwarto mo.', exampleEng: 'Fix your room.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Mag-ayos', phonetic: 'mag-a-yos', meaning: 'To clean up / tidy', exampleFil: 'Mag-ayos ka ng bahay bago umalis.', exampleEng: 'Clean up the house before leaving.', category: 'home', difficulty: Difficulty.intermediate },
  { word: 'Kapitbahay', phonetic: 'ka-pit-ba-hay', meaning: 'Neighbour', exampleFil: 'Mabait ang aming kapitbahay.', exampleEng: 'Our neighbour is kind.', category: 'home', difficulty: Difficulty.intermediate },
  { word: 'Pader', phonetic: 'pa-der', meaning: 'Wall', exampleFil: 'May larawan sa pader.', exampleEng: 'There is a picture on the wall.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Sahig', phonetic: 'sa-hig', meaning: 'Floor', exampleFil: 'Punasan mo ang sahig.', exampleEng: 'Wipe the floor.', category: 'home', difficulty: Difficulty.beginner },
  { word: 'Aparador', phonetic: 'a-pa-ra-dor', meaning: 'Cabinet / Wardrobe', exampleFil: 'Nasa aparador ang damit ko.', exampleEng: 'My clothes are in the wardrobe.', category: 'home', difficulty: Difficulty.intermediate },
  { word: 'Silangang', phonetic: 'si-la-ngan', meaning: 'Sunrise side / East (figurative)', exampleFil: 'Ang bahay namin ay nakaharap sa silangan.', exampleEng: 'Our house faces east.', category: 'home', difficulty: Difficulty.advanced },

  // EMOTIONS (25)
  { word: 'Masaya', phonetic: 'ma-sa-ya', meaning: 'Happy', exampleFil: 'Masaya ako ngayon.', exampleEng: "I'm happy today.", category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Malungkot', phonetic: 'ma-lung-kot', meaning: 'Sad', exampleFil: 'Bakit ka malungkot?', exampleEng: 'Why are you sad?', category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Galit', phonetic: 'ga-lit', meaning: 'Angry', exampleFil: 'Galit siya sa nangyari.', exampleEng: 'He/she is angry about what happened.', category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Takot', phonetic: 'ta-kot', meaning: 'Fear / Scared', exampleFil: 'Takot ako sa dilim.', exampleEng: "I'm scared of the dark.", category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Pagod', phonetic: 'pa-god', meaning: 'Tired', exampleFil: 'Pagod na ako sa trabaho.', exampleEng: "I'm tired from work.", category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Inaantok', phonetic: 'i-na-an-tok', meaning: 'Sleepy', exampleFil: 'Inaantok na ako.', exampleEng: "I'm already sleepy.", category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Excited', phonetic: 'ek-say-ted', meaning: 'Excited', exampleFil: 'Excited na ako sa bakasyon.', exampleEng: "I'm excited for the vacation.", category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Nahihiya', phonetic: 'na-hi-hi-ya', meaning: 'Shy / Embarrassed', exampleFil: 'Nahihiya akong magsalita.', exampleEng: "I'm shy to speak.", category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Nag-aalala', phonetic: 'nag-a-a-la-la', meaning: 'Worried', exampleFil: 'Nag-aalala ako sa kanya.', exampleEng: "I'm worried about him/her.", category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Gulat', phonetic: 'gu-lat', meaning: 'Surprised', exampleFil: 'Nagulat ako sa balita.', exampleEng: 'I was surprised by the news.', category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Nainis', phonetic: 'na-i-nis', meaning: 'Annoyed / Irritated', exampleFil: 'Nainis ako sa ingay.', exampleEng: 'I was annoyed by the noise.', category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Natutuwa', phonetic: 'na-tu-tu-wa', meaning: 'Pleased / Delighted', exampleFil: 'Natutuwa ako sa regalo.', exampleEng: "I'm pleased with the gift.", category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Mahal', phonetic: 'ma-hal', meaning: 'Love (feeling)', exampleFil: 'Puno ng mahal ang puso ko.', exampleEng: 'My heart is full of love.', category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Lungkot', phonetic: 'lung-kot', meaning: 'Sadness / Grief', exampleFil: 'Puno ng lungkot ang kanyang puso.', exampleEng: 'His/her heart is full of sadness.', category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Saya', phonetic: 'sa-ya', meaning: 'Joy / Happiness', exampleFil: 'Puno ng saya ang handaan.', exampleEng: 'The party is full of joy.', category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Hiya', phonetic: 'hi-ya', meaning: 'Shame / Shyness (cultural value)', exampleFil: 'May hiya pa siya.', exampleEng: 'He/she still has shame (is modest).', category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Inis', phonetic: 'i-nis', meaning: 'Annoyance / Irritation', exampleFil: 'Puno na ang inis ko.', exampleEng: "I've had enough of the annoyance.", category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Inggit', phonetic: 'ing-git', meaning: 'Jealousy / Envy', exampleFil: 'Wag kang mag-inggit.', exampleEng: "Don't be jealous.", category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Selos', phonetic: 'se-los', meaning: 'Jealousy (romantic)', exampleFil: 'Naiinggit siya, may selos.', exampleEng: "He/she is envious, there's jealousy.", category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Awa', phonetic: 'a-wa', meaning: 'Pity / Compassion', exampleFil: 'Naawa ako sa kanila.', exampleEng: 'I felt pity for them.', category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Tuwa', phonetic: 'tu-wa', meaning: 'Delight / Gladness', exampleFil: 'Puno ng tuwa ang bata.', exampleEng: 'The child is full of delight.', category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Takot na takot', phonetic: 'ta-kot na ta-kot', meaning: 'Very scared / Terrified', exampleFil: 'Takot na takot siya sa kidlat.', exampleEng: 'He/she is terrified of lightning.', category: 'emotions', difficulty: Difficulty.intermediate },
  { word: 'Natutulig', phonetic: 'na-tu-tu-lig', meaning: 'Confused / Overwhelmed', exampleFil: 'Natutulig na ako sa dami ng problema.', exampleEng: "I'm overwhelmed by so many problems.", category: 'emotions', difficulty: Difficulty.advanced },
  { word: 'Umiyak', phonetic: 'u-mi-yak', meaning: 'To cry', exampleFil: 'Umiyak siya nang marinig ang balita.', exampleEng: 'He/she cried upon hearing the news.', category: 'emotions', difficulty: Difficulty.beginner },
  { word: 'Natawa', phonetic: 'na-ta-wa', meaning: 'Laughed / Found funny', exampleFil: 'Natawa ako sa kanyang joke.', exampleEng: 'I laughed at his/her joke.', category: 'emotions', difficulty: Difficulty.beginner },

  // COMMON PHRASES (25)
  { word: 'Oo', phonetic: 'o-o', meaning: 'Yes', exampleFil: 'Oo, tama ka.', exampleEng: 'Yes, you are correct.', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Hindi', phonetic: 'hin-di', meaning: 'No / Not', exampleFil: 'Hindi ko alam.', exampleEng: "I don't know.", category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Siguro', phonetic: 'si-gu-ro', meaning: 'Maybe / Perhaps', exampleFil: 'Siguro bukas na lang.', exampleEng: 'Maybe tomorrow instead.', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Dito', phonetic: 'di-to', meaning: 'Here', exampleFil: 'Hintay ka dito.', exampleEng: 'Wait here.', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Doon', phonetic: 'do-on', meaning: 'There (far)', exampleFil: 'Nasa doon ang tindahan.', exampleEng: 'The store is over there.', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Ngayon', phonetic: 'nga-yon', meaning: 'Now / Today', exampleFil: 'Ngayon na tayo umalis.', exampleEng: "Let's leave now.", category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Mamaya', phonetic: 'ma-ma-ya', meaning: 'Later', exampleFil: 'Mamaya na lang.', exampleEng: 'Later instead.', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Bukas', phonetic: 'bu-kas', meaning: 'Tomorrow / Open', exampleFil: 'Bukas na lang tayo.', exampleEng: "Let's do it tomorrow.", category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Kahapon', phonetic: 'ka-ha-pon', meaning: 'Yesterday', exampleFil: 'Kahapon pa iyon.', exampleEng: 'That was yesterday already.', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Bakit?', phonetic: 'ba-kit', meaning: 'Why?', exampleFil: 'Bakit ka nalungkot?', exampleEng: 'Why are you sad?', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Paano?', phonetic: 'pa-a-no', meaning: 'How?', exampleFil: 'Paano mo ginawa iyon?', exampleEng: 'How did you do that?', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Ano?', phonetic: 'a-no', meaning: 'What?', exampleFil: 'Ano ang sinabi mo?', exampleEng: 'What did you say?', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Sino?', phonetic: 'si-no', meaning: 'Who?', exampleFil: 'Sino ang dumating?', exampleEng: 'Who arrived?', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Kailan?', phonetic: 'ka-i-lan', meaning: 'When?', exampleFil: 'Kailan kayo aalis?', exampleEng: 'When will you leave?', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Pasensya na', phonetic: 'pa-sen-sya na', meaning: 'Sorry / Please be patient', exampleFil: 'Pasensya na, huli ako.', exampleEng: 'Sorry, I am late.', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Teka lang', phonetic: 'te-ka lang', meaning: 'Wait a moment', exampleFil: 'Teka lang, darating na ako.', exampleEng: 'Wait a moment, I am coming.', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Alam mo ba?', phonetic: 'a-lam mo ba', meaning: 'Do you know?', exampleFil: 'Alam mo ba ang sagot?', exampleEng: 'Do you know the answer?', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Hindi ko alam', phonetic: 'hin-di ko a-lam', meaning: "I don't know", exampleFil: 'Hindi ko alam ang tamang sagot.', exampleEng: "I don't know the correct answer.", category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Naiintindihan mo ba?', phonetic: 'na-i-in-tin-di-han mo ba', meaning: 'Do you understand?', exampleFil: 'Naiintindihan mo ba ang sinabi ko?', exampleEng: 'Do you understand what I said?', category: 'common_phrases', difficulty: Difficulty.intermediate },
  { word: 'Naiintindihan ko', phonetic: 'na-i-in-tin-di-han ko', meaning: 'I understand', exampleFil: 'Naiintindihan ko na.', exampleEng: 'I already understand.', category: 'common_phrases', difficulty: Difficulty.intermediate },
  { word: 'Ulitin mo nga', phonetic: 'u-li-tin mo nga', meaning: 'Please repeat that', exampleFil: 'Ulitin mo nga, hindi ko narinig.', exampleEng: "Please repeat that, I didn't hear.", category: 'common_phrases', difficulty: Difficulty.intermediate },
  { word: 'Mayroon / Meron', phonetic: 'may-ro-on / me-ron', meaning: 'There is / There are / Have', exampleFil: 'Mayroon ba kayong tubig?', exampleEng: 'Do you have water?', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Pwede ba?', phonetic: 'pwe-de ba', meaning: 'Is it okay? / May I?', exampleFil: 'Pwede ba akong sumama?', exampleEng: 'May I come along?', category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Siyempre', phonetic: 'syem-pre', meaning: 'Of course', exampleFil: 'Siyempre, tulungan kita.', exampleEng: "Of course, I'll help you.", category: 'common_phrases', difficulty: Difficulty.beginner },
  { word: 'Ganoon ba?', phonetic: 'ga-no-on ba', meaning: 'Is that so? / Really?', exampleFil: 'Ganoon ba? Hindi ko alam.', exampleEng: "Is that so? I didn't know.", category: 'common_phrases', difficulty: Difficulty.beginner },
];

const lessons = [
  {
    title: 'Po at Opo — Respeto sa Wikang Filipino',
    slug: 'po-at-opo',
    orderIndex: 1,
    difficulty: Difficulty.beginner,
    contentJson: {
      sections: [
        {
          type: 'explanation',
          content: 'In Filipino culture, respect is shown through language. The particles "po" and "opo" are added to sentences when speaking to elders or people you respect.',
        },
        {
          type: 'rule',
          title: 'Po',
          content: '"Po" is added to statements and questions. Example: "Kumain na po ako." (I have already eaten, respectfully.)',
        },
        {
          type: 'rule',
          title: 'Opo',
          content: '"Opo" replaces "Oo" (yes) when speaking respectfully. Example: "Opo, nandito na po ako." (Yes, I am already here.)',
        },
        {
          type: 'cultural_note',
          content: 'Using "po" and "opo" is not optional in Filipino culture — omitting them when speaking to elders can be seen as rude. Children are taught to use them from a very young age.',
        },
      ],
      quiz: [
        {
          id: 'q1',
          question: 'What is the respectful way to say "yes" in Filipino?',
          options: ['Oo', 'Opo', 'Po', 'Hindi'],
          correct: 1,
        },
        {
          id: 'q2',
          question: 'Which sentence correctly uses "po"?',
          options: [
            'Kumain ako po.',
            'Kumain na po ako.',
            'Po kumain na ako.',
            'Ako po kumain na.',
          ],
          correct: 1,
        },
        {
          id: 'q3',
          question: 'When should you use "po" and "opo"?',
          options: [
            'Only with strangers',
            'Only in formal settings',
            'When speaking to elders or people you respect',
            'Only when asking for something',
          ],
          correct: 2,
        },
        {
          id: 'q4',
          question: 'How do you say "No, I don\'t know" respectfully?',
          options: ['Hindi ko alam', 'Hindi po ko alam', 'Hindi ko po alam', 'Po hindi ko alam'],
          correct: 2,
        },
        {
          id: 'q5',
          question: '"Opo" replaces which word?',
          options: ['Hindi', 'Oo', 'Po', 'Sige'],
          correct: 1,
        },
      ],
    },
  },
  {
    title: 'Mga Pagbati — Greetings and Farewells',
    slug: 'mga-pagbati',
    orderIndex: 2,
    difficulty: Difficulty.beginner,
    contentJson: {
      sections: [
        {
          type: 'explanation',
          content: 'Filipinos greet based on the time of day and use different expressions for different situations. Greetings are an important part of Filipino social culture.',
        },
        {
          type: 'vocabulary',
          items: [
            { word: 'Magandang umaga', meaning: 'Good morning' },
            { word: 'Magandang hapon', meaning: 'Good afternoon' },
            { word: 'Magandang gabi', meaning: 'Good evening' },
            { word: 'Kamusta ka?', meaning: 'How are you?' },
            { word: 'Mabuti naman', meaning: "I'm fine / Pretty good" },
            { word: 'Paalam', meaning: 'Goodbye' },
            { word: 'Ingat ka', meaning: 'Take care' },
          ],
        },
        {
          type: 'cultural_note',
          content: '"Kumain ka na ba?" (Have you eaten yet?) is a common Filipino greeting that shows care and concern. It is not always a literal question — it is a way of expressing warmth.',
        },
      ],
      quiz: [
        {
          id: 'q1',
          question: 'How do you say "Good morning" in Filipino?',
          options: ['Magandang gabi', 'Magandang hapon', 'Magandang umaga', 'Kamusta'],
          correct: 2,
        },
        {
          id: 'q2',
          question: 'What does "Ingat ka" mean?',
          options: ['Good morning', 'Take care', 'Goodbye', 'How are you?'],
          correct: 1,
        },
        {
          id: 'q3',
          question: '"Kumain ka na ba?" literally means:',
          options: ['Where are you going?', 'Are you tired?', 'Have you eaten yet?', 'How are you?'],
          correct: 2,
        },
        {
          id: 'q4',
          question: 'What is the appropriate response to "Kamusta ka?"',
          options: ['Paalam', 'Mabuti naman, ikaw?', 'Magandang umaga', 'Salamat'],
          correct: 1,
        },
        {
          id: 'q5',
          question: 'Which greeting is used in the evening?',
          options: ['Magandang umaga', 'Magandang hapon', 'Magandang gabi', 'Kamusta'],
          correct: 2,
        },
      ],
    },
  },
  {
    title: 'Mga Pangngalan — Basic Nouns and the Home',
    slug: 'mga-pangngalan',
    orderIndex: 3,
    difficulty: Difficulty.beginner,
    contentJson: {
      sections: [
        {
          type: 'explanation',
          content: 'Nouns in Filipino are called "pangngalan". Unlike English, Filipino nouns do not change based on gender. The plural is formed by adding "mga" before the noun.',
        },
        {
          type: 'rule',
          title: 'Forming plurals',
          content: 'Add "mga" before the noun. Example: "bahay" (house) → "mga bahay" (houses). "bata" (child) → "mga bata" (children).',
        },
        {
          type: 'vocabulary',
          items: [
            { word: 'Bahay', meaning: 'House' },
            { word: 'Kwarto', meaning: 'Room / Bedroom' },
            { word: 'Kusina', meaning: 'Kitchen' },
            { word: 'Banyo', meaning: 'Bathroom' },
            { word: 'Sala', meaning: 'Living room' },
            { word: 'Mesa', meaning: 'Table' },
            { word: 'Kama', meaning: 'Bed' },
          ],
        },
      ],
      quiz: [
        {
          id: 'q1',
          question: 'How do you make a noun plural in Filipino?',
          options: ['Add -s at the end', 'Add "mga" before the noun', 'Change the vowel', 'Add "ang" before the noun'],
          correct: 1,
        },
        {
          id: 'q2',
          question: 'What does "kusina" mean?',
          options: ['Bedroom', 'Bathroom', 'Kitchen', 'Living room'],
          correct: 2,
        },
        {
          id: 'q3',
          question: 'How do you say "houses" in Filipino?',
          options: ['bahays', 'mga bahay', 'ang bahay', 'bahay-bahay'],
          correct: 1,
        },
        {
          id: 'q4',
          question: 'Which word means "bedroom"?',
          options: ['Sala', 'Banyo', 'Kusina', 'Kwarto'],
          correct: 3,
        },
        {
          id: 'q5',
          question: 'What does "banyo" mean?',
          options: ['Kitchen', 'Bathroom', 'Living room', 'Bedroom'],
          correct: 1,
        },
      ],
    },
  },
  {
    title: 'Mga Panghalip — Pronouns',
    slug: 'mga-panghalip',
    orderIndex: 4,
    difficulty: Difficulty.beginner,
    contentJson: {
      sections: [
        {
          type: 'explanation',
          content: 'Filipino pronouns are different from English. One important distinction: "kami" means "we" excluding the person you are speaking to, while "tayo" means "we" including the person you are speaking to.',
        },
        {
          type: 'vocabulary',
          items: [
            { word: 'Ako', meaning: 'I / Me' },
            { word: 'Ikaw / Ka', meaning: 'You (singular)' },
            { word: 'Siya', meaning: 'He / She / They (singular)' },
            { word: 'Kami', meaning: 'We (excluding you)' },
            { word: 'Tayo', meaning: 'We (including you)' },
            { word: 'Kayo', meaning: 'You (plural) / You (respectful singular)' },
            { word: 'Sila', meaning: 'They (plural)' },
          ],
        },
        {
          type: 'cultural_note',
          content: '"Kayo" can be used as a respectful "you" when addressing a single elder, similar to the Spanish "usted". This is common in formal or respectful speech.',
        },
      ],
      quiz: [
        {
          id: 'q1',
          question: 'What is the difference between "kami" and "tayo"?',
          options: [
            'Kami is formal, tayo is informal',
            'Kami excludes the listener, tayo includes the listener',
            'Kami is singular, tayo is plural',
            'There is no difference',
          ],
          correct: 1,
        },
        {
          id: 'q2',
          question: 'Which pronoun means "he" or "she"?',
          options: ['Ako', 'Ikaw', 'Siya', 'Sila'],
          correct: 2,
        },
        {
          id: 'q3',
          question: '"Kain tayo!" means "Let\'s eat!" — why is "tayo" used here?',
          options: [
            'Because it is formal',
            'Because it includes the person being spoken to',
            'Because it is plural',
            'Because it refers to the past',
          ],
          correct: 1,
        },
        {
          id: 'q4',
          question: 'How do you say "I" in Filipino?',
          options: ['Siya', 'Ikaw', 'Kami', 'Ako'],
          correct: 3,
        },
        {
          id: 'q5',
          question: '"Sila" refers to:',
          options: ['I', 'You (plural)', 'They (plural)', 'We'],
          correct: 2,
        },
      ],
    },
  },
  {
    title: 'Mga Numero — Numbers 1 to 100',
    slug: 'mga-numero',
    orderIndex: 5,
    difficulty: Difficulty.beginner,
    contentJson: {
      sections: [
        {
          type: 'explanation',
          content: 'Filipino has its own number system. Numbers 11–19 are formed with "labin-" prefix. Tens use the "-mpu" suffix pattern. Spanish-derived numbers (uno, dos, tres) are also widely used in everyday speech.',
        },
        {
          type: 'vocabulary',
          items: [
            { word: 'Isa', meaning: '1' },
            { word: 'Dalawa', meaning: '2' },
            { word: 'Tatlo', meaning: '3' },
            { word: 'Apat', meaning: '4' },
            { word: 'Lima', meaning: '5' },
            { word: 'Anim', meaning: '6' },
            { word: 'Pito', meaning: '7' },
            { word: 'Walo', meaning: '8' },
            { word: 'Siyam', meaning: '9' },
            { word: 'Sampu', meaning: '10' },
            { word: 'Labinisa', meaning: '11' },
            { word: 'Dalawampu', meaning: '20' },
            { word: 'Isang daan', meaning: '100' },
          ],
        },
        {
          type: 'rule',
          title: 'Tens pattern',
          content: 'Twenty = Dalawampu, Thirty = Tatlumpu, Forty = Apatnapu, Fifty = Limampu, Sixty = Animnapu, Seventy = Pitumpu, Eighty = Walumpu, Ninety = Siyamnapu.',
        },
      ],
      quiz: [
        {
          id: 'q1',
          question: 'How do you say "five" in Filipino?',
          options: ['Apat', 'Anim', 'Lima', 'Pito'],
          correct: 2,
        },
        {
          id: 'q2',
          question: 'What does "Sampu" mean?',
          options: ['Seven', 'Eight', 'Nine', 'Ten'],
          correct: 3,
        },
        {
          id: 'q3',
          question: 'How do you say "twenty" in Filipino?',
          options: ['Dalawa', 'Dalawampu', 'Labindalawa', 'Tatlumpu'],
          correct: 1,
        },
        {
          id: 'q4',
          question: '"Labin-" is a prefix used for:',
          options: ['Numbers 1–9', 'Numbers 11–19', 'Tens (20, 30, 40)', 'Hundreds'],
          correct: 1,
        },
        {
          id: 'q5',
          question: 'How do you say "one hundred"?',
          options: ['Sampu', 'Isang daan', 'Isang libo', 'Dalawampu'],
          correct: 1,
        },
      ],
    },
  },
  {
    title: 'Pagkain — Food and Dining',
    slug: 'pagkain',
    orderIndex: 6,
    difficulty: Difficulty.beginner,
    contentJson: {
      sections: [
        {
          type: 'explanation',
          content: 'Food is central to Filipino culture. Meals are shared events and offering food to guests is a sign of hospitality. "Kain na!" (Let\'s eat!) is one of the most common and welcoming phrases.',
        },
        {
          type: 'vocabulary',
          items: [
            { word: 'Kanin', meaning: 'Cooked rice (the base of every Filipino meal)' },
            { word: 'Ulam', meaning: 'Main dish eaten with rice' },
            { word: 'Masarap', meaning: 'Delicious' },
            { word: 'Gutom', meaning: 'Hungry' },
            { word: 'Busog', meaning: 'Full (after eating)' },
            { word: 'Magkano?', meaning: 'How much?' },
            { word: 'Palengke', meaning: 'Wet market' },
          ],
        },
        {
          type: 'cultural_note',
          content: 'Rice ("kanin") is served with almost every meal in the Philippines. "Ulam" refers to any dish eaten alongside rice. Saying "masarap!" to a host is one of the kindest compliments you can give.',
        },
      ],
      quiz: [
        {
          id: 'q1',
          question: 'What does "ulam" mean?',
          options: ['Rice', 'Main dish eaten with rice', 'Dessert', 'Snack'],
          correct: 1,
        },
        {
          id: 'q2',
          question: 'How do you say "delicious" in Filipino?',
          options: ['Gutom', 'Busog', 'Masarap', 'Mura'],
          correct: 2,
        },
        {
          id: 'q3',
          question: '"Busog na ako" means:',
          options: ["I'm hungry", "I'm full", "I'm eating", "It's delicious"],
          correct: 1,
        },
        {
          id: 'q4',
          question: 'What is a "palengke"?',
          options: ['A restaurant', 'A wet market', 'A snack', 'A kitchen'],
          correct: 1,
        },
        {
          id: 'q5',
          question: 'What does "Magkano?" mean?',
          options: ['Where is it?', 'What is it?', 'How much?', 'How many?'],
          correct: 2,
        },
      ],
    },
  },
];

async function main() {
  console.log('Seeding cards...');
  for (const card of cards) {
    await prisma.card.upsert({
      where: { id: card.word },
      update: {},
      create: { ...card, id: undefined },
    });
  }
  console.log(`Seeded ${cards.length} cards.`);

  console.log('Seeding lessons...');
  for (const lesson of lessons) {
    await prisma.lesson.upsert({
      where: { slug: lesson.slug },
      update: {},
      create: lesson,
    });
  }
  console.log(`Seeded ${lessons.length} lessons.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
